package uk.gov.justice.digital.oasys.api;

public enum SentencePlanNeeds {
    ACCOMMODATION(),
    ALCOHOL_MISUSE,
    ATTITUDES,
    DRUG_MISUSE,
    EDUCATION_TRAINING_AND_EMPLOYABILITY,
    EMOTIONAL_WELLBEING,
    FINANCIAL_MANAGEMENT_AND_INCOME,
    LIFESTYLE_AND_ASSOCIATES,
    PHYSICAL_HEALTH_IMMEDIATE_ISSUES,
    RELATIONSHIPS
}
