branch-defaults:
  master:
    environment: assessments-api-dev
  feature*:
    environment: assessments-api-dev

deploy:
  artifact: Dockerrun.aws.json
global:
  application_name: assessments-api
  default_platform: arn:aws:elasticbeanstalk:eu-west-2::platform/Docker running on
    64bit Amazon Linux/2.12.1
  default_region: eu-west-2
