apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.name" . }}
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: {{ .Values.secrets.SPRING_DATASOURCE_USERNAME | b64enc | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.SPRING_DATASOURCE_PASSWORD | b64enc | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.secrets.SPRING_DATASOURCE_URL | b64enc | quote }}
  OAUTH_PUBLIC_KEY: {{ .Values.secrets.OAUTH_PUBLIC_KEY | b64enc | quote }}