spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.Oracle10gDialect
    hikari:
      connectionInitSql: alter session set current_schema=EOR

    properties:
      hibernate:
        show_sql: true

    profiles:
      include: logstash