server:
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol_header: x-forwarded-proto

spring:
  datasource:
    data:
  jpa:
    hibernate:
      ddl-auto: create

graceful:
  shutdown:
    enabled: false