spring:
  application:
    name: offender-assessment-api
  cache:
    cache-names: users
    caffeine:
      spec: expireAfterWrite=2m
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/auth/issuer
  flyway:
    enabled: false



  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true

server:
  port: 8080
  servlet:
    context-path: /
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol_header: x-forwarded-proto

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'health, info, ping, mappings'
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-components: always
      show-details: never
    info:
      cache:
        time-to-live: 2000ms

jwt:
  public:
    key: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS1NSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQW1YSWc4S2EzZ1ROcDB2RVBPWCtnU2lsdDdQL1lnR21lVENtVHMzcHhmY2NlUk5idDc4ZlBSd0ZsaXV5UngvNTRsbDFjRDlYTE1EZjNNZ2NpTVJURDU1c3IvTnNJTnVRTWVaM3NVYjFXUktiMEh2QlRzejhrNGZ4blYzS1orYVRnbmFWRHZUcDdzVlpnRFlrdjhVbW1mdUE5RCtjeThLY2p5amhxakFPU3ZZeXR4bTNPS2pabXhWcE1lUERwa2Rtc1VlVXBVQUZLUUZNUmlFeXJ6QmhveEI3THFRQlg1djExd3FMZEEyKytYTnVpcFMwdmJDUzlnVVVpL3Y5SHdjR29ENXpqcTFkMElhRkRoS3lHMVRoTjFjd25xQjREV1A1T3BTSk5HQktRNmRNM0RXd3FjNVhaTTJGdFhnR1hYYkVPK3lqZjVNVUc1eHJQelpCQTNmMDN3d0lEQVFBQi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ==

appinsights:
  instrumentationkey:

azure:
  application-insights:
    web:
      enable-W3C: true

graceful:
  shutdown:
    enabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate: INFO
    uk:
      gov: INFO
  uris:
    exclude:
      regex: /health|/info|/ping|/swagger.*|/webjars/.*|/v2/api-docs
