spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.Oracle10gDialect
    hikari:
      connectionInitSql: alter session set current_schema=EOR
      maximum-pool-size: 5
      connectionTimeout: 1000
      validationTimeout:  500

    properties:
      hibernate:
        show_sql: false

    profiles:
      include: logstash

  flyway:
    enabled: false