server:
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol_header: x-forwarded-proto

spring:
  datasource:
    url: 'jdbc:h2:mem:testdb;Mode=Oracle'
    type: com.zaxxer.hikari.HikariDataSource

  h2:
    console:
      enabled: true

  flyway:
    enabled: true

graceful:
  shutdown:
    enabled: false