version: 2.1
commands:
  setup:
    description: "Install tools and configure kubectl"
    steps:
      - aws-cli/install
      - kubernetes/install
      - helm/install-helm-client:
          version: v3.0.2
      - run:
          name: Setup kubectl
          command: |
            echo -n "${KUBE_ENV_CACERT}" | base64 -d > /tmp/cluster_ca.crt
            kubectl config set-cluster "${KUBE_ENV_NAMESPACE}" \
              --certificate-authority="/tmp/cluster_ca.crt" \
              --server="${KUBE_API_URL}"
            kubectl config set-credentials circleci \
              --token="${KUBE_ENV_TOKEN}"
            kubectl config set-context circleci \
              --cluster="${KUBE_ENV_NAMESPACE}" \
              --user="circleci" \
              --namespace="${KUBE_ENV_NAMESPACE}"
            # confirm setup is ok
            kubectl config use-context circleci
  deploy_to_env:
    parameters:
      env:
        type: string
    steps:
      - setup
      - checkout:
          path: ~/git
      - attach_workspace:
          at: ~/app
      - deploy:
          name: Deploy to << parameters.env >>
          command: |
            APP_VERSION=$(cat ~/app/app_version.txt)
            sed -i "s/appVersion: \".*\"/appVersion: \"${APP_VERSION}\"/g" ~/git/helm_deploy/offender-assessments-api/Chart.yaml
            aws secretsmanager --region ${AWS_DEFAULT_REGION} get-secret-value --secret-id ${KUBE_ENV_NAMESPACE} | jq -r .SecretString | \
            helm upgrade offender-assessments-api ~/git/helm_deploy/offender-assessments-api/. \
            --install --wait --reset-values --timeout 5m --history-max 10 \
              --namespace=${KUBE_ENV_NAMESPACE} \
              --values ~/git/helm_deploy/values-<< parameters.env >>.yaml \
              --values - \
              --set image.tag="${APP_VERSION}"
executors:
  deployer:
    docker:
      - image: circleci/python:3
    working_directory: ~/app
  builder:
    docker:
      - image: circleci/openjdk:11-jdk-browsers
    working_directory: ~/app
  sonar-scanner:
    docker:
      - image: sonarsource/sonar-scanner-cli:4.2
        environment:
          SONAR_HOST_URL: https://pcs-sonarqube.apps.live-1.cloud-platform.service.justice.gov.uk/
          SONAR_PROJECT_KEY: offender-assessment-api
    working_directory: ~/app

orbs:
  aws-cli: circleci/aws-cli@0.1.18
  kubernetes: circleci/kubernetes@0.10.1
  helm: circleci/helm@0.2.3
  owasp: entur/owasp@0.0.6

jobs:
  build:
    executor: builder
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
            - gradle-
      - run: ./gradlew build
      - run:
          name: Record the Application Version
          command: |
            jar xvf build/libs/offender-assessments-api-*.jar BOOT-INF/classes/META-INF/build-info.properties
            APP_VERSION=$(grep 'build.version=' BOOT-INF/classes/META-INF/build-info.properties | awk -F= '{print $2}')
            rm BOOT-INF/classes/META-INF/build-info.properties

            # make up a good version name
            TAG=${APP_VERSION}.${CIRCLE_BRANCH}
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              TAG=${APP_VERSION}
            fi
            echo $TAG > ./app_version.txt

      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
      - persist_to_workspace:
          root: .
          paths:
            - build/libs
            - build.gradle
            - app_version.txt

  build_docker:
    executor: deployer
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build container and publish to docker hub
          command: |
            APP_VERSION=$(cat ./app_version.txt)
            docker build --rm=false . \
               --tag "mojdigitalstudio/offender-assessments-api:$APP_VERSION" \
               --label "maintainer=stuart.whitlam@digital.justice.gov.uk" \
               --label "app.version=$APP_VERSION" \
               --label "build.version=$APP_VERSION" \
               --label "build.number=$CIRCLE_BUILD_NUM" \
               --label "build.url=$CIRCLE_BUILD_URL" \
               --label "build.gitref=$CIRCLE_SHA1"

            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              # publish to docker hub as the tag
             docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
             docker tag mojdigitalstudio/offender-assessments-api:$APP_VERSION mojdigitalstudio/offender-assessments-api:latest
             docker push mojdigitalstudio/offender-assessments-api:$APP_VERSION
             docker push mojdigitalstudio/offender-assessments-api:latest
            fi

  trivy-scan:
    executor: deployer
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - setup_remote_docker
      - run:
          name: Fetch latest image
          command: |
            docker pull mojdigitalstudio/offender-assessments-api:latest
            docker tag mojdigitalstudio/offender-assessments-api:latest mojdigitalstudio/offender-assessments-api:trivy-scan
      - run:
          name: Install trivy
          command: |
            VERSION=$(
                curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | \
                grep '"tag_name":' | \
                sed -E 's/.*"v([^"]+)".*/\1/'
            )
            wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
            tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz
            sudo mv trivy /usr/local/bin
      - run:
          name: Scan the local image with trivy
          command: |
            mkdir -p build/reports/trivy
            trivy \
              --exit-code 0 \
              --no-progress \
              -f json \
              -o build/reports/trivy/report.json \
              -s "HIGH,CRITICAL" \
              "mojdigitalstudio/offender-assessments-api:trivy-scan"
      - persist_to_workspace:
          root: .
          paths:
            - build/reports/trivy

  sonar-scan:
    executor: sonar-scanner
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Run sonar scan
          command: |
            set -euo pipefail
            declare -a args
            add_env_var_as_env_prop() {
              if [ "$1" ]; then
                args+=("-D$2=$1")
              fi
            }
            add_env_var_as_env_prop "${SONAR_LOGIN:-}" "sonar.login"
            add_env_var_as_env_prop "${SONAR_PASSWORD:-}" "sonar.password"
            add_env_var_as_env_prop "${SONAR_USER_HOME:-}" "sonar.userHome"
            add_env_var_as_env_prop "${SONAR_PROJECT_BASE_DIR:-}" "sonar.projectBaseDir"
            add_env_var_as_env_prop "${SONAR_PROJECT_KEY:-}" "sonar.projectKey"
            PROJECT_BASE_DIR="$PWD"
            if [ "${SONAR_PROJECT_BASE_DIR:-}" ]; then
              PROJECT_BASE_DIR="${SONAR_PROJECT_BASE_DIR}"
            fi
            export SONAR_USER_HOME="$PROJECT_BASE_DIR/.sonar"
            sonar-scanner "${args[@]}"

  deploy_dev:
    executor: deployer
    steps:
      - deploy_to_env:
          env: "development"
  deploy_preprod:
    executor: deployer
    steps:
      - deploy_to_env:
          env: "preprod"
  deploy_prod:
    executor: deployer
    steps:
      - deploy_to_env:
          env: "prod"

workflows:
  version: 2
  scheduled:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - owasp/gradle_owasp_dependency_check:
          executor: builder
          persist_to_workspace: true
      - trivy-scan
      - sonar-scan:
          requires:
            - build
            - owasp/gradle_owasp_dependency_check
            - trivy-scan
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - build_docker:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy_dev:
          requires:
            - build_docker
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - deploy_preprod:
          context: offender-assessments-api-preprod
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - deploy_prod:
          context: offender-assessments-api-prod
          requires:
            - request-prod-approval
