SET REFERENTIAL_INTEGRITY FALSE;

INSERT INTO OFFENDER (OFFENDER_PK,LIMITED_ACCESS_OFFENDER,PNC,CMS_PROB_NUMBER,CMS_PRIS_NUMBER,LEGACY_CMS_PROB_NUMBER,CRO_NUMBER,PRISON_NUMBER,MERGE_PNC_NUMBER,FAMILY_NAME,FORENAME_1,FORENAME_2,FORENAME_3,RISK_TO_OTHERS_ELM, RISK_TO_SELF_ELM,PRIMARY_LOCATION_AREA,CREATE_USER,LASTUPD_USER)
VALUES (1234,'Y','PNC','CRN','NOMIS','LEGACYCMS','CRO','BOOKIN','MPNC','Offender', 'Mike','Tom', 'Steve', 'Y', 'N','ANY','ANY','ANY');


INSERT INTO OASYS_ASSESSMENT_GROUP (OASYS_ASSESSMENT_GROUP_PK, OFFENDER_PK, ASSESSMENT_DATE_CLOSED, HISTORIC_STATUS_ELM, CREATE_DATE, CREATE_USER, LASTUPD_USER)
VALUES (6542, 1234, null, 'OTHER', TO_DATE('2018-08-16 10:16:36', 'YYYY-MM-DD HH24:MI:SS'), 'PROBATION1', 'SYS'),
       (6543, 1234, null, 'CURRENT', TO_DATE('2018-10-16 10:16:36', 'YYYY-MM-DD HH24:MI:SS'), 'PROBATION1', 'SYS');


-- The ref assessment version is from V1_98.sql
INSERT INTO OASYS_SET (OASYS_SET_PK, ASSESSMENT_VOIDED_DATE, ASSESSOR_NAME, OASYS_SCORING_ALG_VERSION, CREATE_DATE,  DATE_COMPLETED, ASSESSMENT_TYPE_ELM, ASSESSMENT_STATUS_ELM, OASYS_ASSESSMENT_GROUP_PK, REF_ASS_VERSION_CODE, VERSION_NUMBER, ASSESSMENT_STATUS_CAT,
    OGP_ST_WESC,
	OGP_DY_WESC,
	OGP_TOT_WESC,
	OVP_ST_WESC,
	OVP_DY_WESC,
	OVP_TOT_WESC,
	OGRS3_1YEAR,
	OGRS3_2YEAR,
	OGRS3_RISK_RECON_ELM,
	OGRS3_RISK_RECON_CAT,
	OGP_1YEAR,
	OGP_2YEAR,
	OGP_RISK_RECON_ELM,
	OGP_RISK_RECON_CAT,
	OVP_1YEAR,
	OVP_2YEAR,
	OVP_RISK_RECON_ELM,
	OVP_RISK_RECON_CAT,
	OVP_PREV_WESC,
	OVP_VIO_WESC,
	OVP_NON_VIO_WESC,
	OVP_AGE_WESC,
	OVP_SEX_WESC,
 CREATE_USER, LASTUPD_USER)
VALUES
    (5430, null, 'Probation Test', 1, TO_DATE('2018-05-19 23:00:09', 'YYYY-MM-DD HH24:MI:SS'), null, 'LAYER_3', 'COMPLETE', 6542, 'LAYER3', '1', 'ANY',
    3, 7, 10, 14, 3, 17, 3, 5, 'L', 'RISK_FLAG', 4, 8, 'L', 'RISK_FLAG', 4, 7, 'L', 'RISK_FLAG', 5, 4, 0, 0, 5,
    'ANY', 'ANY'),
       (5431, TO_DATE('2018-06-20 23:00:09', 'YYYY-MM-DD HH24:MI:SS'), 'Probation Test', 1, TO_DATE('2018-05-21 23:00:09', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2018-07-21 23:00:09', 'YYYY-MM-DD HH24:MI:SS'), 'LAYER_3', 'COMPLETE', 6543, 'LAYER3', '1', 'ANY',
       3, 7, 10, 14, 3, 17, 3, 5, 'L', 'RISK_FLAG', 4, 8, 'L', 'RISK_FLAG', 4, 7, 'L', 'RISK_FLAG', 5, 4, 0, 0, 5,
       'ANY', 'ANY')