SET REFERENTIAL_INTEGRITY FALSE;

INSERT INTO OFFENDER (OFFENDER_PK,LIMITED_ACCESS_OFFENDER,PNC,CMS_PROB_NUMBER,CMS_PRIS_NUMBER,LEGACY_CMS_PROB_NUMBER,CRO_NUMBER,PRISON_NUMBER,MERGE_PNC_NUMBER,FAMILY_NAME,FORENAME_1,FORENAME_2,FORENAME_3,RISK_TO_OTHERS_ELM, RISK_TO_SELF_ELM,PRIMARY_LOCATION_AREA,CREATE_USER,LASTUPD_USER)
VALUES (1234,'Y','PNC','CRN','NOMIS','LEGACYCMS','CRO','BOOKIN','MPNC','Offender', 'Mike','Tom', 'Steve', 'Y', 'N','ANY','ANY','ANY');

-- deleted offender with duplicate identifiers
INSERT INTO OFFENDER (OFFENDER_PK,LIMITED_ACCESS_OFFENDER,PNC,CMS_PROB_NUMBER,CMS_PRIS_NUMBER,LEGACY_CMS_PROB_NUMBER,CRO_NUMBER,PRISON_NUMBER,MERGE_PNC_NUMBER,FAMILY_NAME,FORENAME_1,FORENAME_2,FORENAME_3,RISK_TO_OTHERS_ELM, RISK_TO_SELF_ELM,PRIMARY_LOCATION_AREA,CREATE_USER,LASTUPD_USER,DELETED_DATE)
VALUES (4321,'Y','PNC','CRN','NOMIS','LEGACYCMS','CRO','BOOKIN','MPNC','Offender', 'Mike','Tom', 'Steve', 'Y', 'N','ANY','ANY','ANY', TO_DATE('2010-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO OFFENDER (OFFENDER_PK,LIMITED_ACCESS_OFFENDER,PNC,CMS_PROB_NUMBER,CMS_PRIS_NUMBER,LEGACY_CMS_PROB_NUMBER,CRO_NUMBER,PRISON_NUMBER,MERGE_PNC_NUMBER,FAMILY_NAME,FORENAME_1,FORENAME_2,FORENAME_3,RISK_TO_OTHERS_ELM, RISK_TO_SELF_ELM,PRIMARY_LOCATION_AREA,CREATE_USER,LASTUPD_USER,DELETED_DATE)
VALUES (9876,'Y','DPNC','DCRN','DNOMIS','DLEGACYCM','DCRO','DBOOK','DMPNC','Offender', 'Mike','Tom', 'Steve', 'Y', 'N','ANY','ANY','ANY', TO_DATE('2010-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

-- offenders with duplicate identifiers
INSERT INTO OFFENDER (OFFENDER_PK,LIMITED_ACCESS_OFFENDER,PNC,CMS_PROB_NUMBER,CMS_PRIS_NUMBER,LEGACY_CMS_PROB_NUMBER,CRO_NUMBER,PRISON_NUMBER,MERGE_PNC_NUMBER,FAMILY_NAME,FORENAME_1,FORENAME_2,FORENAME_3,RISK_TO_OTHERS_ELM, RISK_TO_SELF_ELM,PRIMARY_LOCATION_AREA,CREATE_USER,LASTUPD_USER)
VALUES (1212,'Y','PNCD','CRND','NOMISD','LEGACYCMSD','CROD','BOOKD','MPNCD','Offender', 'Mike','Tom', 'Steve', 'Y', 'N','ANY','ANY','ANY');

INSERT INTO OFFENDER (OFFENDER_PK,LIMITED_ACCESS_OFFENDER,PNC,CMS_PROB_NUMBER,CMS_PRIS_NUMBER,LEGACY_CMS_PROB_NUMBER,CRO_NUMBER,PRISON_NUMBER,MERGE_PNC_NUMBER,FAMILY_NAME,FORENAME_1,FORENAME_2,FORENAME_3,RISK_TO_OTHERS_ELM, RISK_TO_SELF_ELM,PRIMARY_LOCATION_AREA,CREATE_USER,LASTUPD_USER)
VALUES (2121,'Y','PNCD','CRND','NOMISD','LEGACYCMSD','CROD','BOOKD','MPNCD','Offender', 'Mike','Tom', 'Steve', 'Y', 'N','ANY','ANY','ANY');



--Merged Offenders

--1 merge
INSERT INTO OFFENDER (OFFENDER_PK,LIMITED_ACCESS_OFFENDER,PNC,CMS_PROB_NUMBER,CMS_PRIS_NUMBER,LEGACY_CMS_PROB_NUMBER,CRO_NUMBER,PRISON_NUMBER,MERGE_PNC_NUMBER,FAMILY_NAME,FORENAME_1,FORENAME_2,FORENAME_3,RISK_TO_OTHERS_ELM, RISK_TO_SELF_ELM,PRIMARY_LOCATION_AREA,CREATE_USER,LASTUPD_USER,MERGED_IND,DELETED_DATE) VALUES
(100,'Y','PNC1','CRN1','NOMIS1','LEGACYCMS1','CRO1','BOOK1','MPNC1','Offender 1', 'Offender 1','Offender 1', 'Offender 1', 'Y', 'N','ANY','ANY','ANY', 'Y', TO_DATE('2019-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')),
(200,'Y','PNC1','CRN1','NOMIS1','LEGACYCMS1','CRO1','BOOK1','MPNC1','Offender 2', 'Offender 2','Offender 2', 'Offender 2', 'Y', 'N','ANY','ANY','ANY', 'Y', TO_DATE('2019-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')),
(300,'Y','PNC1','CRN1','NOMIS1','LEGACYCMS1','CRO1','BOOK1','MPNC1','Offender 1', 'Offender 1','Offender 1', 'Offender 1', 'Y', 'N','ANY','ANY','ANY', 'N', NULL),

--2 merges
(400,'Y','PNC4','CRN4','NOMIS4','LEGACYCMS4','CRO4','BOOK4','MPNC4','Offender 4', 'Offender 4','Offender 4', 'Offender 4', 'Y', 'N','ANY','ANY','ANY', 'Y', TO_DATE('2019-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')),
(500,'Y','PNC4','CRN4','NOMIS4','LEGACYCMS4','CRO4','BOOK4','MPNC4','Offender 5', 'Offender 5','Offender 5', 'Offender 5', 'Y', 'N','ANY','ANY','ANY', 'Y', TO_DATE('2019-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')),
(600,'Y','PNC4','CRN4','NOMIS4','LEGACYCMS4','CRO4','BOOK4','MPNC4','Offender 5', 'Offender 5','Offender 5', 'Offender 5', 'Y', 'N','ANY','ANY','ANY', 'Y', TO_DATE('2019-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')),

(700,'Y','PNC4','CRN4','NOMIS4','LEGACYCMS4','CRO4','BOOK4','MPNC4','Offender 7', 'Offender 7','Offender 7', 'Offender 7', 'Y', 'N','ANY','ANY','ANY', 'Y', TO_DATE('2019-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS')),
(800,'Y','PNC4','CRN4','NOMIS4','LEGACYCMS4','CRO4','BOOK4','MPNC4','Offender 5', 'Offender 5','Offender 5', 'Offender 5', 'Y', 'N','ANY','ANY','ANY', 'N', NULL);


INSERT INTO OFFENDER_LINK (OFFENDER_LINK_PK, INITIATING_OFFENDER, DECIDING_OFFENDER, MERGED_OFFENDER, LINK_TYPE_ELM, LINK_TYPE_CAT, CREATE_USER, LASTUPD_USER) VALUES
(100, 200, 100, 300, 'MERGE_RETAIN', 'LINK_TYPE', 'ANY', 'ANY'),
(200, 400, 500, 600, 'MERGE_RELINQUISH', 'LINK_TYPE', 'ANY', 'ANY'),
(300, 700, 600, 800, 'MERGE_RETAIN', 'LINK_TYPE', 'ANY', 'ANY');