SET REFERENTIAL_INTEGRITY FALSE;

INSERT INTO OFFENDER (OFFENDER_PK,LIMITED_ACCESS_OFFENDER,PNC,CMS_PROB_NUMBER,CMS_PRIS_NUMBER,LEGACY_CMS_PROB_NUMBER,CRO_NUMBER,PRISON_NUMBER,MERGE_PNC_NUMBER,FAMILY_NAME,FORENAME_1,FORENAME_2,FORENAME_3,RISK_TO_OTHERS_ELM, RISK_TO_SELF_ELM,PRIMARY_LOCATION_AREA,CREATE_USER,LASTUPD_USER)
VALUES (1234,'Y','PNC','CRN','NOMIS','LEGACYCMS','CRO','BOOKIN','MPNC','Offender', 'Mike','Tom', 'Steve', 'Y', 'N','ANY','ANY','ANY');
