DELETE FROM OFFENDER where OFFENDER_PK = 1234;

DELETE FROM OASYS_SET where OASYS_SET_PK = 5430;
DELETE FROM OASYS_SET where OASYS_SET_PK = 5431;
DELETE FROM OASYS_SET where OASYS_SET_PK = 5432;
DELETE FROM OASYS_SET where OASYS_SET_PK = 5433;
DELETE FROM OASYS_SET where OASYS_SET_PK = 5434;

DELETE FROM OASYS_ASSESSMENT_GROUP where OASYS_ASSESSMENT_GROUP_PK = 6542;
DELETE FROM OASYS_ASSESSMENT_GROUP where OASYS_ASSESSMENT_GROUP_PK = 6543;