package uk.gov.justice.digital.oasys.utils;

public enum LogEvent {
    OFFENDER_NOT_FOUND,
    ASSESSMENT_NOT_FOUND,
    SECTION_NOT_FOUND,
    QUESTION_NOT_FOUND,
    UNCAUGHT_EXCEPTION,
    USER_AUTHENTICATION_ATTEMPT,
    USER_AUTHENTICATION_PARSE_ERROR,
    USER_AUTHENTICATION,
    USER_SERVICE_ERROR,

    GET_SECTION_FOUND,
    GET_SECTION_NOT_FOUND,
    GET_SECTIONS_FOUND,
    GET_ASSESSMENTS,
    GET_ASSESSMENT_FOUND,
    GET_ASSESSMENT_NOT_FOUND,
    GET_LATEST_ASSESSMENT_FOUND,
    GET_LATEST_ASSESSMENT_NOT_FOUND,

    GET_ASSESSMENT,
    GET_ASSESSMENT_SUMMARY,
    GET_ASSESSMENT_SUMMARY_FOUND,
    GET_USER_AUTH,
    GET_REF_DATA_BY_CATEGORY,
    GET_FULL_SP_LIST,
    GET_FULL_SP_LIST_FOUND,
    GET_FULL_SP,
    GET_FULL_SP_FOUND,
    GET_FULL_SP_NOT_FOUND,
    GET_LATEST_FULL_SP,
    GET_LATEST_BASIC_SP,
    GET_BASIC_SP,
    GET_BASIC_SP_NOT_FOUND,
    GET_LATEST_ASSESSMENT,
    GET_OFFENDER_SUMMARY,
    GET_OFFENDER_SUMMARY_FOUND,
    DUPLICATE_OFFENDER_FOUND,
    GET_SUMMARY_SP_LIST,
    GET_SUMMARY_SP_LIST_FOUND,
    GET_SUMMARY_SP, GET_OFFENDER_OGP, GET_OFFENDER_OGP_FOUND, GET_OFFENDER_PREDICTORS, GET_OFFENDER_PREDICTORS_FOUND;
    public static final String EVENT = "event_id";
    public static final String EXCEPTION = "exception";
}
