# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: docker.io/mojdigitalstudio/offender-assessments-api
  tag: latest
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: offender-prprod.aks-live-1.studio-hosting.service.justice.gov.uk
      cert_secret: offender-assessments-api-preprod-tls-secret
  path: /

env:
  JAVA_OPTS: "-Xmx512m -Duser.timezone=UTC"
  TZ: UTC
  OAUTH_ENDPOINT_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth

