# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.io/mojdigitalstudio/offender-assessments-api
  tag: latest
  pullPolicy: Always
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/whitelist-source-range: "217.33.148.210/32,81.134.202.29/32,52.56.175.16/32,35.177.252.195/32"
  hosts:
    - host: assessment-api.hmpps.dsd.io
      cert_secret: assessment-api-cert
  path: /

env:
  JAVA_OPTS: "-Xmx512m"
