# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.io/mojdigitalstudio/offender-assessments-api
  tag: latest
  pullPolicy: Always
  port: 8080

env:
  JAVA_OPTS: "-Xmx512m"
