
create table REF_CATEGORY
(
	REF_CATEGORY_UK NUMBER not null
		constraint REF_CATEGORY_UN
			unique,
	REF_CATEGORY_CODE VARCHAR2(50) not null
		constraint REF_CATEGORY_PK
			primary key,
	CAT_CODE_DESC VARCHAR2(4000),
	OPOL_IND VARCHAR2(1) default 'N' not null,
	ADD_ALLOWED_IND VARCHAR2(1) default 'N' not null,
	UPDATE_ALLOWED_IND VARCHAR2(1) default 'N' not null,
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null
);


create table REF_CATEGORY_COLUMN
(
	REF_CATEGORY_COLUMN_UK NUMBER not null
		constraint REF_CATEGORY_COLUMN_UN
			unique,
	TABLE_NAME VARCHAR2(40) not null,
	COLUMN_NAME VARCHAR2(100) not null,
	REF_CATEGORY_CODE VARCHAR2(50) not null
		constraint RCT_RCD
			references REF_CATEGORY,
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null,
	constraint REF_CATEGORY_COLUMN_PK
		primary key (TABLE_NAME, COLUMN_NAME, REF_CATEGORY_CODE)
);


create table REF_ELEMENT
(
	REF_ELEMENT_UK NUMBER not null
		constraint REF_ELEMENT_UN
			unique,
	REF_CATEGORY_CODE VARCHAR2(50) not null
		constraint RCT_REL
			references REF_CATEGORY,
	REF_ELEMENT_CODE VARCHAR2(50) not null,
	REF_ELEMENT_CTID VARCHAR2(50),
	REF_ELEMENT_SHORT_DESC VARCHAR2(60),
	REF_ELEMENT_DESC VARCHAR2(4000),
	DISPLAY_SORT NUMBER,
	START_DATE DATE not null,
	END_DATE DATE,
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null,
	constraint REF_ELEMENT_PK
		primary key (REF_CATEGORY_CODE, REF_ELEMENT_CODE)
);


create table COURT
(
	COURT_PK NUMBER not null
		constraint COURT_PK
			primary key,
	COURT_CODE VARCHAR2(100) not null
		constraint COURT_UN
			unique,
	COURT_NAME VARCHAR2(100) not null,
	COURT_TYPE_ELM VARCHAR2(50) not null,
	COURT_TYPE_CAT VARCHAR2(50) not null,
	LOCAL_JUSTICE_AREA_ELM VARCHAR2(50),
	LOCAL_JUSTICE_AREA_CAT VARCHAR2(50),
	START_DATE DATE not null,
	END_DATE DATE,
	GENERAL_CODE VARCHAR2(100),
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null,
	constraint ELM_FK33
		foreign key (COURT_TYPE_CAT, COURT_TYPE_ELM) references REF_ELEMENT,
	constraint ELM_FK36
		foreign key (LOCAL_JUSTICE_AREA_CAT, LOCAL_JUSTICE_AREA_ELM) references REF_ELEMENT
);


create table CT_AREA_EST
(
	CT_AREA_EST_UK NUMBER not null
		constraint CT_AREA_EST_UN
			unique,
	CT_AREA_EST_CODE VARCHAR2(100) not null
		constraint CT_AREA_EST_PK
			primary key,
	AREA_EST_CTID VARCHAR2(50),
	AREA_EST_NAME VARCHAR2(100),
	START_DATE DATE not null,
	END_DATE DATE,
	CASE_MAN_SYSTEM_ELM VARCHAR2(50),
	CASE_MAN_SYSTEM_CAT VARCHAR2(50),
	SERVICE_ELM VARCHAR2(50),
	SERVICE_CAT VARCHAR2(50),
	LAO_CONTACT_NUMBER VARCHAR2(100),
	SHOW_SDR_OBJ_IND VARCHAR2(1) default 'N' not null,
	SHOW_SDR_HINTS_IND VARCHAR2(1) default 'N' not null,
	SHOW_CRIM_GRAPH_IND VARCHAR2(1) default 'N' not null,
	SHOW_SDR_EVIDENCE_ELM VARCHAR2(50),
	SHOW_SDR_EVIDENCE_CAT VARCHAR2(50),
	SDR_CONCERN_NONE_IND VARCHAR2(1) default 'N' not null,
	SDR_CONCERN_SUICIDE_IND VARCHAR2(1) default 'N' not null,
	SDR_CONCERN_SELFHARM_IND VARCHAR2(1) default 'N' not null,
	SDR_CONCERN_CUSTODY_IND VARCHAR2(1) default 'N' not null,
	SDR_CONCERN_HOSTEL_IND VARCHAR2(1) default 'N' not null,
	SDR_CONCERN_VULNERABLE_IND VARCHAR2(1) default 'N' not null,
	DEF_TEAM_DIVISION_CODE VARCHAR2(100),
	USER_MAIN_CONTACT VARCHAR2(100),
	DEF_TEAM_CODE VARCHAR2(100),
	DATA_EXPORT_PATH VARCHAR2(1024),
	OASYS_USER_CODE VARCHAR2(100),
	NOMIS_CODE VARCHAR2(6),
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null,
	PSR_LOGO_FILENAME VARCHAR2(4000),
	AREA_EST_TYPE_CAT VARCHAR2(50),
	AREA_EST_TYPE_ELM VARCHAR2(50),
	RUN_QA_SAMPLE_IND VARCHAR2(1)
		check ( run_qa_sample_ind IN ('N' , 'Y' )),
	BCS_ON_RECEPTION_IND VARCHAR2(1)
		check ( bcs_on_reception_ind IN ('N' , 'Y' )),
	constraint ELM_FK43
		foreign key (CASE_MAN_SYSTEM_CAT, CASE_MAN_SYSTEM_ELM) references REF_ELEMENT,
	constraint ELM_FK44
		foreign key (SERVICE_CAT, SERVICE_ELM) references REF_ELEMENT,
	constraint ELM_FK45
		foreign key (SHOW_SDR_EVIDENCE_CAT, SHOW_SDR_EVIDENCE_ELM) references REF_ELEMENT,
	constraint ELM_FKX50
		foreign key (AREA_EST_TYPE_CAT, AREA_EST_TYPE_ELM) references REF_ELEMENT
);


create table AREA_EST_COURT
(
	AREA_EST_COURT_UK NUMBER not null
		constraint AREA_EST_COURT_UN
			unique,
	CT_AREA_EST_CODE VARCHAR2(100) not null
		constraint CAE_AEC
			references CT_AREA_EST,
	COURT_PK NUMBER not null
		constraint CRT_AEC
			references COURT,
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null,
	constraint AREA_EST_COURT_PK
		primary key (COURT_PK, CT_AREA_EST_CODE)
);


create table AREA_INTERVENTION
(
	AREA_INTERVENTION_UK NUMBER not null
		constraint AREA_INTERVENTION_UN
			unique,
	INTERVENTION_ELM VARCHAR2(50) not null,
	INTERVENTION_CAT VARCHAR2(50) not null,
	CT_AREA_EST_CODE VARCHAR2(100) not null
		constraint CAE_AIN
			references CT_AREA_EST,
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null,
	constraint AREA_INTERVENTION_PK
		primary key (INTERVENTION_CAT, INTERVENTION_ELM, CT_AREA_EST_CODE),
	constraint ELM_FK42
		foreign key (INTERVENTION_CAT, INTERVENTION_ELM) references REF_ELEMENT
);


create table DIVISION
(
	DIVISION_UK NUMBER not null
		constraint DIVISION_UN
			unique,
	CT_AREA_EST_CODE VARCHAR2(100) not null
		constraint CAE_DIV
			references CT_AREA_EST,
	DIVISION_CODE VARCHAR2(100) not null,
	DIVISION_NAME VARCHAR2(100),
	START_DATE DATE not null,
	END_DATE DATE,
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null,
	constraint DIVISION_PK
		primary key (CT_AREA_EST_CODE, DIVISION_CODE)
);



create table OBJECTIVE
(
	OBJECTIVE_UK NUMBER not null
		constraint OBJECTIVE_UN
			unique,
	OBJECTIVE_CODE VARCHAR2(100) not null
		constraint OBJECTIVE_PK
			primary key,
	OBJECTIVE_DESC VARCHAR2(100),
	OBJECTIVE_HEADING_ELM VARCHAR2(50) not null,
	OBJECTIVE_HEADING_CAT VARCHAR2(50) not null,
	START_DATE DATE not null,
	END_DATE DATE,
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null,
	constraint ELM_FK93
		foreign key (OBJECTIVE_HEADING_CAT, OBJECTIVE_HEADING_ELM) references REF_ELEMENT
);


create table OFFICE
(
	OFFICE_UK NUMBER not null
		constraint OFFICE_UN
			unique,
	OFFICE_CODE VARCHAR2(100) not null,
	CT_AREA_EST_CODE VARCHAR2(100) not null
		constraint CAE_OFC
			references CT_AREA_EST,
	OFFICE_NAME VARCHAR2(100),
	START_DATE DATE not null,
	END_DATE DATE,
	ADDRESS_LINE_1 VARCHAR2(256),
	ADDRESS_LINE_2 VARCHAR2(256),
	ADDRESS_LINE_3 VARCHAR2(256),
	ADDRESS_LINE_4 VARCHAR2(256),
	ADDRESS_LINE_5 VARCHAR2(256),
	ADDRESS_LINE_6 VARCHAR2(256),
	POSTCODE VARCHAR2(32),
	CONTACT_NUMBER VARCHAR2(32),
	OFFICE_FAX_NUMBER VARCHAR2(20),
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null,
	constraint OFFICE_PK
		primary key (CT_AREA_EST_CODE, OFFICE_CODE)
);

create table REF_MODULE
(
	REF_MODULE_UK NUMBER not null
		constraint REF_MODULE_UN
			unique,
	REF_MODULE_CODE VARCHAR2(100) not null
		constraint REF_MODULE_PK
			primary key,
	MODULE_DESC VARCHAR2(1024),
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null
);


create table REF_ASS_VERSION
(
	REF_ASS_VERSION_UK NUMBER not null
		constraint REF_ASS_VERSION_UN
			unique,
	REF_ASS_VERSION_CODE VARCHAR2(100) not null,
	VERSION_NUMBER VARCHAR2(100) not null,
	START_DATE DATE not null,
	END_DATE DATE,
	ASSESSMENT_TYPE_ELM VARCHAR2(50),
	ASSESSMENT_TYPE_CAT VARCHAR2(50),
	OASYS_FORM_VERSION NUMBER,
	OASYS_SCORING_ALG_VERSION NUMBER,
	REF_MODULE_CODE VARCHAR2(100) not null
		constraint RMO_RAV
			references REF_MODULE,
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null,
	constraint REF_ASS_VERSION_PK
		primary key (REF_ASS_VERSION_CODE, VERSION_NUMBER),
	constraint ELM_FK119
		foreign key (ASSESSMENT_TYPE_CAT, ASSESSMENT_TYPE_ELM) references REF_ELEMENT
);


create table REF_ROLE
(
	REF_ROLE_UK NUMBER not null
		constraint REF_ROLE_UN
			unique,
	REF_ROLE_CODE VARCHAR2(100) not null
		constraint REF_ROLE_PK
			primary key,
	REF_ROLE_DESC VARCHAR2(100),
	ROLE_TYPE_ELM VARCHAR2(50) not null,
	ROLE_TYPE_CAT VARCHAR2(100) not null,
	CT_AREA_EST_CODE VARCHAR2(100)
		constraint CAE_RRO
			references CT_AREA_EST,
	RESTRICTED_IND VARCHAR2(1) default 'N' not null,
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null,
	constraint ELM_FK127
		foreign key (ROLE_TYPE_CAT, ROLE_TYPE_ELM) references REF_ELEMENT
);




create table REF_FUNCTION
(
	REF_FUNCTION_UK NUMBER not null
		constraint REF_FUNCTION_UN
			unique,
	REF_FUNCTION_CODE VARCHAR2(100) not null
		constraint REF_FUNCTION_PK
			primary key,
	FUNCTION_DESC VARCHAR2(100),
	FUNCTION_TYPE_ELM VARCHAR2(50) not null,
	FUNCTION_TYPE_CAT VARCHAR2(50) not null,
	ASSESSMENT_TYPE_ELM VARCHAR2(50),
	ASSESSMENT_TYPE_CAT VARCHAR2(50),
	SECTION_TYPE_ELM VARCHAR2(50),
	SECTION_TYPE_CAT VARCHAR2(50),
	SIGNOFF_TYPE_ELM VARCHAR2(50),
	SIGNOFF_TYPE_CAT VARCHAR2(50),
	OWN_OFFENDER_IND VARCHAR2(1) default 'N' not null,
	RBAC_TYPE_ELM VARCHAR2(50),
	RBAC_TYPE_CAT VARCHAR2(50),
	FUNCTION_GROUP_ELM VARCHAR2(50),
	FUNCTION_GROUP_CAT VARCHAR2(50),
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null,
	constraint ELM_FK120
		foreign key (FUNCTION_GROUP_CAT, FUNCTION_GROUP_ELM) references REF_ELEMENT,
	constraint ELM_FK121
		foreign key (FUNCTION_TYPE_CAT, FUNCTION_TYPE_ELM) references REF_ELEMENT,
	constraint ELM_FK122
		foreign key (ASSESSMENT_TYPE_CAT, ASSESSMENT_TYPE_ELM) references REF_ELEMENT,
	constraint ELM_FK123
		foreign key (SECTION_TYPE_CAT, SECTION_TYPE_ELM) references REF_ELEMENT,
	constraint ELM_FK124
		foreign key (SIGNOFF_TYPE_CAT, SIGNOFF_TYPE_ELM) references REF_ELEMENT,
	constraint ELM_FK125
		foreign key (RBAC_TYPE_CAT, RBAC_TYPE_ELM) references REF_ELEMENT
);


create table REF_ROLE_FUNCTION
(
	REF_ROLE_FUNCTION_UK NUMBER not null
		constraint REF_ROLE_FUNCTION_UN
			unique,
	REF_FUNCTION_CODE VARCHAR2(100) not null
		constraint OFU_ORF
			references REF_FUNCTION,
	REF_ROLE_CODE VARCHAR2(100) not null
		constraint RRO_RRF
			references REF_ROLE
				on delete cascade,
	START_DATE DATE not null,
	END_DATE DATE,
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null,
	constraint REF_ROLE_FUNCTION_PK
		primary key (REF_FUNCTION_CODE, REF_ROLE_CODE)
);


create table REF_SECTION
(
	REF_SECTION_UK NUMBER not null
		constraint REF_SECTION_UN
			unique,
	REF_ASS_VERSION_CODE VARCHAR2(100) not null,
	VERSION_NUMBER VARCHAR2(100) not null,
	REF_SECTION_CODE VARCHAR2(100) not null,
	FORM_SEQUENCE NUMBER,
	SECTION_TYPE_ELM VARCHAR2(50),
	SECTION_TYPE_CAT VARCHAR2(50),
	CRIM_NEED_SCORE_THRESHOLD NUMBER,
	SCORED_FOR_OGP VARCHAR2(1) default 'N' not null,
	SCORED_FOR_OVP VARCHAR2(1) default 'N' not null,
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null,
	constraint REF_SECTION_PK
		primary key (REF_SECTION_CODE, REF_ASS_VERSION_CODE, VERSION_NUMBER),
	constraint ELM_FK3
		foreign key (SECTION_TYPE_CAT, SECTION_TYPE_ELM) references REF_ELEMENT,
	constraint RAV_RSE
		foreign key (REF_ASS_VERSION_CODE, VERSION_NUMBER) references REF_ASS_VERSION
			on delete cascade
);


create table REF_QUESTION
(
	REF_QUESTION_UK NUMBER not null
		constraint REF_QUESTION_UN
			unique,
	REF_ASS_VERSION_CODE VARCHAR2(100) not null,
	VERSION_NUMBER VARCHAR2(100) not null,
	REF_SECTION_CODE VARCHAR2(100) not null,
	REF_QUESTION_CODE VARCHAR2(100) not null,
	DISPLAY_SORT NUMBER,
	REF_SECTION_QUESTION VARCHAR2(4000) not null,
	MANDATORY_IND VARCHAR2(1) default 'N' not null,
	VERSION_NUMBER_PARENT VARCHAR2(100),
	REF_SECTION_CODE_PARENT VARCHAR2(100),
	REF_QUESTION_CODE_PARENT VARCHAR2(100),
	QA_WEIGHTING NUMBER(8,4),
	CT_AREA_EST_CODE VARCHAR2(100)
		constraint CAE_RQU
			references CT_AREA_EST,
	REF_ASS_VERSION_CODE_PARENT VARCHAR2(100),
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null,
	POA_ASSMT_HIDE_IND VARCHAR2(1),
	constraint REF_QUESTION_PK
		primary key (REF_ASS_VERSION_CODE, VERSION_NUMBER, REF_SECTION_CODE, REF_QUESTION_CODE),
	constraint RQU_RQU
		foreign key (REF_ASS_VERSION_CODE_PARENT, VERSION_NUMBER_PARENT, REF_SECTION_CODE_PARENT, REF_QUESTION_CODE_PARENT) references REF_QUESTION
			on delete cascade,
	constraint RSE_RQU
		foreign key (REF_SECTION_CODE, REF_ASS_VERSION_CODE, VERSION_NUMBER) references REF_SECTION
			on delete cascade
);


create table REF_ANSWER
(
	REF_ANSWER_UK NUMBER not null
		constraint REF_ANSWER_UN
			unique,
	REF_ASS_VERSION_CODE VARCHAR2(100) not null,
	VERSION_NUMBER VARCHAR2(100) not null,
	REF_SECTION_CODE VARCHAR2(100) not null,
	REF_QUESTION_CODE VARCHAR2(100) not null,
	REF_ANSWER_CODE VARCHAR2(100) not null,
	DISPLAY_SORT NUMBER,
	REF_SECTION_ANSWER VARCHAR2(4000),
	DEFAULT_DISPLAY_SCORE NUMBER,
	OGP_SCORE NUMBER,
	OVP_SCORE NUMBER,
	CHECKSUM VARCHAR2(4000),
	QA_RAW_SCORE NUMBER(8,4),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null,
	constraint REF_ANSWER_PK
		primary key (REF_ASS_VERSION_CODE, VERSION_NUMBER, REF_SECTION_CODE, REF_QUESTION_CODE, REF_ANSWER_CODE),
	constraint RQU_RAN
		foreign key (REF_ASS_VERSION_CODE, VERSION_NUMBER, REF_SECTION_CODE, REF_QUESTION_CODE) references REF_QUESTION
			on delete cascade
);
