
create table OASYS_USER
(
	OASYS_USER_UK NUMBER not null
		constraint OASYS_USER_UN
			unique,
	OASYS_USER_CODE VARCHAR2(100) not null
		constraint OASYS_USER_PK
			primary key,
	USER_FORENAME_1 VARCHAR2(100),
	USER_FORENAME_2 VARCHAR2(100),
	USER_FORENAME_3 VARCHAR2(100),
	USER_FAMILY_NAME VARCHAR2(100),
	PASSWORD_ENCRYPTED RAW(256),
	PASSWORD_CHANGE_DATE DATE,
	LAST_LOGIN DATE,
	FAILED_LOGIN_ATTEMPTS NUMBER,
	SYSTEM_IND VARCHAR2(1) default 'N' not null,
	USER_STATUS_ELM VARCHAR2(50) default 'ACTIVE' not null,
	USER_STATUS_CAT VARCHAR2(50) default 'USER_STATUS' not null,
	DATE_OF_BIRTH DATE,
	PASSWORD VARCHAR2(30),
	EMAIL_ADDRESS VARCHAR2(100),
	LEGACY_USER_CODE VARCHAR2(100),
	MIGRATION_SOURCE_ELM VARCHAR2(50),
	MIGRATION_SOURCE_CAT VARCHAR2(50),
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null,
	CT_AREA_EST_CODE VARCHAR2(100)
		constraint CAE_USER
			references CT_AREA_EST,
	EXCL_DEACT_IND VARCHAR2(1) default 'N' not null,
	DEACT_USER VARCHAR2(100),
	DEACT_DATE DATE,
	DEACT_REASON VARCHAR2(50),
	LAST_RESET_DATE DATE,
	constraint ELM_FK89
		foreign key (MIGRATION_SOURCE_CAT, MIGRATION_SOURCE_ELM) references REF_ELEMENT,
	constraint ELM_FK90
		foreign key (USER_STATUS_CAT, USER_STATUS_ELM) references REF_ELEMENT
);

create table AREA_EST_USER_ROLE
(
	AREA_EST_USER_ROLE_UK NUMBER not null
		constraint AREA_EST_USER_ROLE_UN
			unique,
	OASYS_USER_CODE VARCHAR2(100) not null
		constraint OUS_AUR
			references OASYS_USER,
	REF_ROLE_CODE VARCHAR2(100) not null
		constraint RRO_AUR
			references REF_ROLE,
	CT_AREA_EST_CODE VARCHAR2(100) not null
		constraint CAE_AUR
			references CT_AREA_EST,
	START_DATE DATE not null,
	END_DATE DATE,
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null,
	constraint OASYS_USER_ROLE_PK
		primary key (OASYS_USER_CODE, REF_ROLE_CODE, CT_AREA_EST_CODE)
);


create table TEAM
(
	TEAM_UK NUMBER not null
		constraint TEAM_UN
			unique,
	CT_AREA_EST_CODE VARCHAR2(100) not null,
	DIVISION_CODE VARCHAR2(100) not null,
	TEAM_CODE VARCHAR2(100) not null,
	TEAM_NAME VARCHAR2(100),
	CONTACT_NUMBER VARCHAR2(32),
	EMAIL_ADDRESS VARCHAR2(100),
	START_DATE DATE not null,
	END_DATE DATE,
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null,
	constraint TEAM_PK
		primary key (DIVISION_CODE, TEAM_CODE, CT_AREA_EST_CODE),
	constraint DIV_TEA
		foreign key (CT_AREA_EST_CODE, DIVISION_CODE) references DIVISION
);


create table USER_AREA
(
	USER_AREA_UK NUMBER not null
		constraint USER_AREA_UN2
			unique,
	CT_AREA_EST_CODE VARCHAR2(100) not null
		constraint CAE_UAR
			references CT_AREA_EST,
	OASYS_USER_CODE VARCHAR2(100) not null
		constraint OUS_UAR
			references OASYS_USER,
	START_DATE DATE not null,
	END_DATE DATE,
	PHONE_NUMBER VARCHAR2(32),
	EMAIL_ADDRESS VARCHAR2(100),
	DEFAULT_TEAM_AREA_EST_CODE VARCHAR2(100),
	DIVISION_CODE VARCHAR2(100),
	TEAM_CODE VARCHAR2(100),
	DEF_CNTRSGN_USER VARCHAR2(100),
	DEF_CNTRSIGN_USER_AREA VARCHAR2(100),
	USER_POSITION VARCHAR2(100),
	HIERARCHY_LEVEL_ELM VARCHAR2(50),
	HIERARCHY_LEVEL_CAT VARCHAR2(50),
	OFFICE_AREA_EST_CODE VARCHAR2(100),
	OFFICE_CODE VARCHAR2(100),
	DELIUS_NOTES_ID VARCHAR2(100),
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null,
	LAST_LOGIN_DATE DATE,
	DEACT_USER VARCHAR2(100),
	DEACT_DATE DATE,
	DEACT_REASON VARCHAR2(50),
	LAST_RESET_DATE DATE,
	constraint USER_AREA_PK
		primary key (OASYS_USER_CODE, CT_AREA_EST_CODE),
	constraint ELM_FK30
		foreign key (HIERARCHY_LEVEL_CAT, HIERARCHY_LEVEL_ELM) references REF_ELEMENT,
	constraint OFC_UAR
		foreign key (OFFICE_AREA_EST_CODE, OFFICE_CODE) references OFFICE,
	constraint TEA_UAR
		foreign key (DIVISION_CODE, TEAM_CODE, DEFAULT_TEAM_AREA_EST_CODE) references TEAM,
	constraint UAR_UAR
		foreign key (DEF_CNTRSGN_USER, DEF_CNTRSIGN_USER_AREA) references USER_AREA
);


create table USER_TEAM
(
	USER_TEAM_UK NUMBER not null
		constraint USER_TEAM_UN
			unique,
	OASYS_USER_CODE VARCHAR2(100) not null
		constraint OUS_UTE
			references OASYS_USER,
	CT_AREA_EST_CODE VARCHAR2(100) not null,
	DIVISION_CODE VARCHAR2(100) not null,
	TEAM_CODE VARCHAR2(100) not null,
	START_DATE DATE not null,
	END_DATE DATE,
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null,
	constraint USER_TEAM_PK
		primary key (OASYS_USER_CODE, TEAM_CODE, DIVISION_CODE, CT_AREA_EST_CODE),
	constraint TEA_UTE
		foreign key (DIVISION_CODE, TEAM_CODE, CT_AREA_EST_CODE) references TEAM
);

