




create table SSP_WHO_DO_WORK_PIVOT
(
	SSP_WHO_DO_WORK_PIVOT_PK NUMBER not null
		constraint SSP_WHO_DO_WORK_PIVOT_PK
			primary key,
	WHO_WORK_OBJ_ELM VARCHAR2(50),
	WHO_WORK_OBJ_CAT VARCHAR2(50),
	COMMENTS VARCHAR2(4000),
	SSP_INTERVENTION_IN_SET_PK NUMBER not null
		constraint SIS_WDW
			references SSP_INTERVENTION_IN_SET
				on delete cascade,
	MIG_GUID VARCHAR2(256),
	MIG_ID VARCHAR2(256),
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null,
	constraint ELM_FK23
		foreign key (WHO_WORK_OBJ_CAT, WHO_WORK_OBJ_ELM) references REF_ELEMENT
);


create table SSP_INTERVENTION_MEASURE
(
	SSP_INTERVENTION_MEASURE_PK NUMBER not null
		constraint SSP_INTERVENTION_MEASURE_PK
			primary key,
	INTERVENE_MEAS_CODE_ELM VARCHAR2(50),
	INTERVENE_MEAS_CODE_CAT VARCHAR2(50),
	SSP_INTERVENTION_IN_SET_PK NUMBER not null
		constraint SIS_SIM
			references SSP_INTERVENTION_IN_SET
				on delete cascade,
	INTERVENE_MEAS_COMMENT CLOB,
	LAST_UPDATE_DATE DATE,
	MIG_GUID VARCHAR2(256),
	MIG_ID VARCHAR2(256),
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null,
	constraint ELM_FK19
		foreign key (INTERVENE_MEAS_CODE_CAT, INTERVENE_MEAS_CODE_ELM) references REF_ELEMENT
);


create table SSP_OBJECTIVES_IN_SET
(
	SSP_OBJECTIVES_IN_SET_PK NUMBER not null
		constraint SSP_OBJECTIVES_IN_SET_PK
			primary key,
	COPIED_FORWARD_INDICATOR VARCHAR2(1) default 'N' not null,
	HOW_PROGRESS_MEASURED CLOB,
	DISPLAY_SORT NUMBER,
	OBJECTIVE_TYPE_ELM VARCHAR2(50),
	OBJECTIVE_TYPE_CAT VARCHAR2(50),
	LAST_UPDATE_DATE DATE,
	OASYS_SET_PK NUMBER not null
		constraint OAS_SOS
			references OASYS_SET
				on delete cascade,
	MIG_GUID VARCHAR2(256),
	MIG_ID VARCHAR2(256),
	CF_LAST_ASSMT_OBJ NUMBER,
	CF_ORIG_ASSMT_OBJ NUMBER,
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null,
	constraint ELM_FK20
		foreign key (OBJECTIVE_TYPE_CAT, OBJECTIVE_TYPE_ELM) references REF_ELEMENT
);






create table SSP_CRIM_NEED_OBJ_PIVOT
(
	SSP_CRIM_NEED_OBJ_PIVOT_PK NUMBER not null
		constraint SSP_CRIM_NEED_OBJ_PIVOT_PK
			primary key,
	CRIMINOGENIC_NEED_ELM VARCHAR2(50),
	CRIMINOGENIC_NEED_CAT VARCHAR2(50),
	DISPLAY_SORT NUMBER,
	SSP_OBJECTIVES_IN_SET_PK NUMBER not null
		constraint SOS_CNO
			references SSP_OBJECTIVES_IN_SET
				on delete cascade,
	MIG_GUID VARCHAR2(256),
	MIG_ID VARCHAR2(256),
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null,
	constraint ELM_FK17
		foreign key (CRIMINOGENIC_NEED_CAT, CRIMINOGENIC_NEED_ELM) references REF_ELEMENT
);


create table SSP_OBJECTIVE_MEASURE
(
	SSP_OBJECTIVE_MEASURE_PK NUMBER not null
		constraint SSP_OBJECTIVE_MEASURE_PK
			primary key,
	OBJECTIVE_STATUS_COMMENTS VARCHAR2(4000),
	OBJECTIVE_STATUS_ELM VARCHAR2(50) default 'R' not null,
	OBJECTIVE_STATUS_CAT VARCHAR2(50) default 'OBJECTIVE_STATUS_CODE' not null,
	SSP_OBJECTIVES_IN_SET_PK NUMBER not null
		constraint SOS_OME
			references SSP_OBJECTIVES_IN_SET
				on delete cascade,
	MIG_GUID VARCHAR2(256),
	MIG_ID VARCHAR2(256),
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null,
	constraint ELM_FK21
		foreign key (OBJECTIVE_STATUS_CAT, OBJECTIVE_STATUS_ELM) references REF_ELEMENT
);


create table SSP_OBJECTIVE
(
	SSP_OBJECTIVE_PK NUMBER not null
		constraint SSP_OBJECTIVE_PK
			primary key,
	OBJECTIVE_DESC CLOB,
	SSP_OBJECTIVES_IN_SET_PK NUMBER not null
		constraint SOB_SOS
			references SSP_OBJECTIVES_IN_SET
				on delete cascade,
	OBJECTIVE_CODE VARCHAR2(100)
		constraint OBJ_SOB
			references OBJECTIVE,
	MIG_GUID VARCHAR2(256),
	MIG_ID VARCHAR2(256),
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null
);




create table SSP_OBJ_INTERVENE_PIVOT
(
	SSP_OBJ_INTERVENE_PIVOT_PK NUMBER not null
		constraint SSP_OBJ_INTERVENE_PIVOT_PK
			primary key,
	SSP_OBJECTIVES_IN_SET_PK NUMBER not null
		constraint SOS_OIP
			references SSP_OBJECTIVES_IN_SET
				on delete cascade,
	SSP_INTERVENTION_IN_SET_PK NUMBER not null
		constraint SIS_OIP
			references SSP_INTERVENTION_IN_SET
				on delete cascade,
	DELETED_IND VARCHAR2(1) default 'N' not null,
	MIG_GUID VARCHAR2(256),
	MIG_ID VARCHAR2(256),
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null,
	constraint SSP_OBJ_INTERVENE_PIVOT_UN
		unique (SSP_OBJECTIVES_IN_SET_PK, SSP_INTERVENTION_IN_SET_PK)
);

create table SSP_CONTRIBUTOR
(
	SSP_CONTRIBUTOR_PK NUMBER not null
		constraint SSP_CONTRIBUTOR_PK
			primary key,
	CONTRIBUTOR_NAME VARCHAR2(256),
	CONTRIBUTOR_ROLE VARCHAR2(256),
	SENT_PLAN_BOARD_ATTD_IND VARCHAR2(1)
		check ( sent_plan_board_attd_ind IN ('N' , 'Y' )),
	DISPLAY_SORT NUMBER,
	CURRENTLY_HIDDEN_IND VARCHAR2(1) default 'N' not null,
	OASYS_SET_PK NUMBER not null
		constraint OAS_CON
			references OASYS_SET
				on delete cascade,
	MIG_GUID VARCHAR2(256),
	MIG_ID VARCHAR2(256),
	CHECKSUM VARCHAR2(4000),
	CREATE_DATE DATE,
	CREATE_USER VARCHAR2(100) not null,
	LASTUPD_DATE DATE,
	LASTUPD_USER VARCHAR2(100) not null
);


